---
- name: Installation install software-properties-common
  apt: name=software-properties-common

- name: Ensure packages needed for nginx+php-fpm are present
  apt: name={{ item }} state=present
  with_items:
    - php7.4
    - php7.4-fpm
    - php7.4-common
    - php7.4-curl
    - php7.4-zip
    - php7.4-gd
    - php7.4-mysql
    - php7.4-xml
    - php7.4-mbstring
    - php7.4-json
    - php7.4-intl
    - php7.4-soap
  notify: restart php7.4-fpm
