FROM python:3.10-alpine

WORKDIR /app/

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY main.py .

RUN crontab -l | { cat; echo "0 * * * * python /app/main.py"; } | crontab -

CMD ['crond']
